name: publish

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  push_to_registry:
    name: build and release
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - id: check-changes
      uses: hashibuto/github-actions/changes-check@changes-check_v0
      with:
        base-branch: master

    - id: check-version
      name: Check release version
      uses: hashibuto/github-actions/version-check@version-check_v0
      with:
        path-prefix: ./

    - name: run tests
      run: make test

    - id: tag-release-version
      name: Tag release version
      if: ${{ steps.check-changes.outputs.is-merged == 'true' }}
      uses: hashibuto/github-actions/version-check@version-check_v0
      with:
        path-prefix: ./
        create-release-tag: true
        create-major-release-tag: false

    - name: Update compare tag
      if: ${{ steps.check-changes.outputs.is-merged == 'true' }}
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.git.updateRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "tags/base",
            sha: "${{ github.sha }}",
            force: true
          })